fix(parser): Fix decimal grammar
The grammer for parsing decimal numbers was incorrect, leading `1.0.1` to be parsed as a valid decimal grammar. Fortunately, this still caused a `FailedToParseBigDecimal` error during parsing, but it should be a `FailedToParse` error instead.

This commit fixes the grammar to correctly parse decimal numbers and ensures that invalid decimal numbers like `1.0.1` are caught as `FailedToParse` errors.

```sh
test parser::tests::test_parse_invalid_decimal ... FAILED

failures:

---- parser::tests::test_parse_invalid_decimal stdout ----

thread 'parser::tests::test_parse_invalid_decimal' panicked at expression-core/src/parser.rs:196:9:
Expected FailedToParse error, got different error: FailedToParseBigDecimal(ParseBigInt(ParseBigIntError { kind: InvalidDigit }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Not that the grammar still allows `00012.1` as a valid decimal number. This will be properly evaluated by the evaluator.

This commit also adds:

- `README`s to improve developer's experience.
- A test for nested function calls.
- A typo fix in the parser.